name: CRDA Python Linter and Docstyle 

on:
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Linter
      run: bash qa/run-linter.sh;
    - name: Run PyDocStyle
      run: bash qa/check-docstyle.sh
    - name: Run Detect common errors
      run: bash qa/detect-common-errors.sh
    - name: Run Detect dead code 
      run:  bash qa/detect-dead-code.sh
    - name: Run Cyclomatic Complexity Check
      run: bash qa/measure-cyclomatic-complexity.sh --fail-on-error
    - name: Run Maintainablity index Check
      run: bash qa/measure-maintainability-index.sh --fail-on-error
